### PR TITLE
Add documentation for include templates

### PR DESCRIPTION
**Pull request by ramazangirgin**

### CODE REVIEW

**Comment by ramazangirgin** [comment]
@lotabout thank you for reviewing PR and merging it.
Could you please also create a release and make it available in Jetrains / Intellij plugin marketplace ? After that, I will be able officially download and install it.

**Comment by lotabout** [comment]
@ramazangirgin Already done that, waiting for Jetbrain's approval.

**Comment by ramazangirgin** [comment]
@lotabout thank you for the answer. I don't see new tag and release in github and for that reason wanted to ask you.
Hope it will be approved soon, waiting for it. 
Thank you.

**Comment by ramazangirgin** [comment]
@lotabout actually it seems it is already accepted and available in plugin store. 
https://plugins.jetbrains.com/plugin/10098-code-generator/versions/stable/174770
thank you.

**Pull request merged**
